### ISSUE TITLE
Running subset install twice actually installs things twice

### ISSUE THREAD

**Issue by marciodsousa** [tabrindle/install-subset#20]
## Problem
One of the commands I run when starting up my dev environment is `subset install x` in case someone else added new dependencies meanwhile. But I noticed that this always takes some time. After some tests, I realised it always behaves as if installing dependencies "from scratch" opposed to `yarn` which by the second time you run it it takes 2s or so because there's nothing new to install.

I know there's an option to clear the node_modules, which I am **not** using. But since under the hood subset install actually runs `yarn install` I'm not 100% sure there's something to be done here in the scope of this project. But any help here would be appreciated :)

**Comment by tabrindle** [comment]
I'm sure there's quite a lot of optimization in yarn via diffing and caching that this library probably breaks. I agree there's really much to be done here.
