### ISSUE TITLE
Frozen Lockfile

### ISSUE THREAD

**Issue by SteffeyDev** [tabrindle/install-subset#21]
It is common on CI servers to use `--frozen-lockfile` when installing build dependencies.  Can I just add a flag to forward `--frozen-lockfile` through to the yarn install command or does frozen lockfile not work due to how you are doing the subset?

**Comment by tabrindle** [comment]
Part of the process is to restore the yarn.lock to its original state, so its function is the same except for throwing a non-zero exit when updates are needed. Don't think that's necessary here. 

Feel free to reopen if this doesn't answer your question!
