### ISSUE TITLE
Error running command on win10

### ISSUE THREAD

**Issue by JustinRainwater** [tabrindle/install-subset#9]
I just discovered this module and was excited because it's exactly what we're looking for. Unfortunately I'm getting errors when trying to install subset on windows. Also the output isn't very helpful:

```C:\Users\Developer\justinTest\sparkler-shell>subset install ui-test

C:\Users\Developer\AppData\Roaming\npm\node_modules\install-subset\index.js:95
      throw 'Error code ' + installer.status;
      ^
Error code null```

Have you tried to run this on windows? Do you expect it to work on windows? Thanks

**Comment by JustinRainwater** [comment]
@tabrindle I just did another search after being able to see the actual error and it looks like this is the issue:
https://github.com/nodejs/node-v0.x-archive/issues/25330#issuecomment-102428996

appending .cmd seems to fix the problem

**Comment by tabrindle** [comment]
Interesting! Since I don't have any access to a windows machine, care to make a PR? We could probably use something like this: https://www.npmjs.com/package/cross-spawn

**Comment by JustinRainwater** [comment]
@tabrindle thanks for the tip on cross-spawn. Way better than the `if win32` check I had. I have a branch with the fix, but I'm not familiar with pushing to other people's public repos in order to create a PR. I get the following error when trying to do git push: `fatal: unable to access 'https://github.com/tabrindle/install-subset.git/': The requested URL returned error: 403`

**Comment by JustinRainwater** [comment]
@tabrindle I created this. Let me know if that works.

https://github.com/tabrindle/install-subset/pull/10/files

**Comment by tabrindle** [comment]
Merged!

**Comment by Ezard** [comment]
@tabrindle any chance you could publish this fix to NPM please? Just run into the same issue myself. Thanks! :)
